// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseDirectory() {
  return window['go']['main']['App']['ChooseDirectory']();
}

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetNotes() {
  return window['go']['main']['App']['GetNotes']();
}

export function ReadNote(arg1) {
  return window['go']['main']['App']['ReadNote'](arg1);
}

export function RenameNote(arg1, arg2) {
  return window['go']['main']['App']['RenameNote'](arg1, arg2);
}

export function SaveNote(arg1, arg2) {
  return window['go']['main']['App']['SaveNote'](arg1, arg2);
}

export function SetDataDir(arg1) {
  return window['go']['main']['App']['SetDataDir'](arg1);
}
