// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ChooseDirectory():Promise<string>;

export function DeleteNote(arg1:string):Promise<void>;

export function GetDataDir():Promise<string>;

export function GetNotes():Promise<Array<main.Note>>;

export function ReadNote(arg1:string):Promise<string>;

export function RenameNote(arg1:string,arg2:string):Promise<string>;

export function SaveNote(arg1:string,arg2:string):Promise<void>;

export function SetDataDir(arg1:string):Promise<void>;
